name: Feedback
description: 'Leave general feedback'
body:
  - type: input
    attributes:
      label: Specific Episode (if applicable)

  - type: textarea
    attributes:
      label: Feedback
    validations:
      required: true
